name: Get 5.19 kernel config
on:
  workflow_dispatch:
jobs:
  Get config:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          DOCKER_IMAGE=ubuntu:22.10
          docker pull ${DOCKER_IMAGE}
          docker run \
          -t \
          -v "$(pwd)":/repo \
          ${DOCKER_IMAGE} \
          /bin/bash -c 'cd /repo && \
          apt update && \
          apt install linux-generic -y && \
          cp -r /boot/config* /repo'
          mkdir /tmp/artifacts
          cp -r "$(pwd)"/* /tmp/artifacts
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: kconfig
          path: /tmp/artifacts/*
