name: Get Kernel config
on:
  workflow_dispatch:
jobs:
  Get-config:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Get kconfig
        run: |
          sudo apt update
          sudo apt install linux-generic
          wget https://raw.githubusercontent.com/pimlie/ubuntu-mainline-kernel.sh/master/ubuntu-mainline-kernel.sh
          chmod +x ubuntu-mainline-kernel.sh
          sudo mv ubuntu-mainline-kernel.sh /usr/local/bin/
          sudo ubuntu-mainline-kernel.sh -i --yes
          mkdir /tmp/artifacts
          cp -r /boot/config* /tmp/artifacts
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: kconfig
          path: /tmp/artifacts/*
