---
name: Mic configuration update script

on:
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout Repo'
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Get the latest package
        id: publish
        run: |
            cd ${{ github.workspace }}
            echo "ver=0.1.0" >> $GITHUB_ENV
            wget https://github.com/lemmyg/t2-apple-audio-dsp/releases/download/mic-v${{ env.ver }}/t2-apple-audio-dsp-mic_${{ env.ver }}_amd64.deb
 
            git clone https://github.com/AdityaGarg8/t2-ubuntu-repo.git
            mv ${{ github.workspace }}/t2-apple-audio-dsp-mic_${{ env.ver }}_amd64.deb ${{ github.workspace }}/t2-ubuntu-repo
            cd ${{ github.workspace }}/t2-ubuntu-repo
            # Packages & Packages.gz
            dpkg-scanpackages --multiversion . > Packages
            gzip -k -f Packages
            # Release, Release.gpg & InRelease
            apt-ftparchive release . > Release
            gpg --default-key "${GPG_SIGNING_EMAIL}" -abs -o - Release > Release.gpg
            gpg --default-key "${GPG_SIGNING_EMAIL}" --clearsign -o - Release > InRelease
            cd ${{ github.workspace }}
           fi
        env:
          GPG_SIGNING_EMAIL: ${{ secrets.GPG_SIGNING_EMAIL }}
      - name: Publish
        if: env.publish == 'yes'
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 't2-ubuntu-repo'
          destination-github-username: 'AdityaGarg8'
          destination-repository-name: 't2-ubuntu-repo'
          user-email: github-actions[bot]@users.noreply.github.com
          user-name: github-actions[bot]
          target-branch: main
          commit-message: Update Mic configuration to v${{ env.ver }}

